name: phoronix-snap # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Phoronix-test-suit tools analys
description: |
  Snap to use the well-known analysis tool phoronix-test-suite. For
  the supported tests, it will remain in the selections in the future,
  focusing on the CPU, Memomy and Kernel categories.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

parts:
  phoronix:
    # See 'snapcraft plugins'
    plugin:
      - home
      - network
