name: phoronix-snap # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Phoronix-test-suit tools analys
description: |
  Snap to use the well-known analysis tool phoronix-test-suite. For
  the supported tests, it will remain in the selections in the future,
  focusing on the CPU, Memomy and Kernel categories.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode

apps:
  phoronix-snap:
    command: bin/phoronix-test-suite
    #environment:
    #  LD_LIBRARY_PATH: $SNAP/usr/share/phoronix-test-suite/

passthrough:
  layout:
    $SNAP/usr/bin/php:
      symlink: $SNAP/usr/bin/php7.4

parts:
  phoronix-snap:
    source: . 
    plugin: dump
    build-packages:
      - php
      - php-cli
      - php-xml
    stage-packages:
      - python
      - python-pexpect
      - php
      - php-cli
      - php-xml
      - libgd3
      - libxpm4
      - libfontconfig1
      - libfreetype6
      - libtiff5
      - psmisc
      - libjbig0
      - ttf-bitstream-vera
      - fonts-freefont-ttf
      - gsfonts-x11
      - xfonts-utils
      - libfontenc1
      - iptables
    override-build: |
      snapcraftctl build
      DESTDIR=/usr
      cd phoronix-test-suite
      ./install-sh
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp /usr/bin/phoronix-test-suite $SNAPCRAFT_PART_INSTALL/bin/phoronix-test-suite
